steps:
  # Build the container image
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/cpd-infrastructure/cpdbackend", "."]
  # Push the container image to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/cpd-infrastructure/cpdbackend"]
  # Deploy container image to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      [
        "run",
        "deploy",
        "cpd-backend",
        "--image",
        "gcr.io/cpd-infrastructure/cpdbackend",
        "--region",
        "us-central1",
        "--platform",
        "managed",
      ]
images:
  - gcr.io/cpd-infrastructure/cpdbackend
